### ISSUE TITLE
Классы

### ISSUE THREAD

**Issue by ramz1t** [ramz1t/diary#1]
class Student:
  __tablename__ = 'students'
  name: str
  login: str
  pass: hash
  id: int
  school_id: int
  marks = relationship(Mark)

class Teacher:
  __tablename__ = 'teachers'
  name: str
  login: str
  pass: hash
  subject: str
  classes: relationship(Group)
  school_id: int
  id: int

class Admin:
  __tablename__ = 'admins'
  login: str
  pass: hash

class Group:
  __tablename__ = 'groups'
  name: str
  students: relationship(Student)
  tasks: relationship(Task)
  teacher: relationship-back(Teacher)

class Mark:
  __tablename__ = 'marks'
  value: int
  student: relationship-back(User)
    
class Task:
  __tablename__ = 'tasks'
  group: relationship-back(Group)
  teacher: relationship-back(Teacher)
  time: TimeDate
  body: str

class School:
  __tablename__ = 'schools'
  name: str
  city: str

**Comment by altr3s** [comment]
i think we need to add id to anybody classes. in commit do this, если что дашь пизды

**Comment by altr3s** [comment]
i think we need to add id to anybody classes. in commit do this, если что дашь пизды
